# Generated by Django 4.1.5 on 2023-07-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Phone', models.BigIntegerField()),
                ('Password', models.CharField(max_length=250)),
                ('JobDescription', models.CharField(max_length=250)),
                ('Status', models.CharField(default='Active', max_length=250)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Student_pinfo',
            fields=[
                ('Student_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('DOB', models.DateField(max_length=10)),
                ('Gender', models.CharField(max_length=250)),
                ('Phone', models.BigIntegerField()),
                ('Street', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Pincode', models.CharField(max_length=250)),
                ('AadharNumber', models.CharField(max_length=250)),
                ('PostalAddress', models.TextField(max_length=250)),
                ('Nationality', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'PersonalInformation',
            },
        ),
        migrations.CreateModel(
            name='Student_sinfo',
            fields=[
                ('Student_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('TotalFee', models.IntegerField()),
                ('InitialPaid', models.IntegerField()),
                ('Balance', models.CharField(max_length=250)),
                ('Class', models.CharField(max_length=250)),
                ('DateJoined', models.DateField(max_length=10)),
                ('ProfilePicture', models.ImageField(max_length=250, upload_to='')),
                ('SignaturePicture', models.ImageField(max_length=250, null=True, upload_to='')),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_pinfo')),
            ],
            options={
                'db_table': 'SchoolInformation',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=250)),
                ('TransactionType', models.CharField(max_length=250)),
                ('Date', models.DateField(auto_now_add=True, max_length=250)),
                ('Time', models.TimeField(auto_now_add=True, max_length=250)),
                ('Status', models.CharField(default='Incomplete', max_length=250)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_sinfo')),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_pinfo')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
